# Generated by Django 3.0.5 on 2023-11-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_remove_result_selected_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(blank=True, choices=[('Subject_One', 'SUBJECT_ONE'), ('Subject_Two', 'SUBJECT_TWO'), ('Subject_Three', 'SUBJECT_THREE'), ('Subject_Four', 'SUBJECT_FOUR'), ('Subject_Five', 'SUBJECT_FIVE'), ('Subject_Six', 'SUBJECT_SIX'), ('Subject_Seven', 'SUBJECT_SEVEN'), ('Subject_Eight', 'SUBJECT_EIGHT'), ('Subject_Nine', 'SUBJECT_NINE'), ('Subject_Ten', 'SUBJECT_TEN'), ('Subject_Eleven', 'SUBJECT_TEN')], max_length=15, null=True),
        ),
    ]
