# Generated by Django 3.0.5 on 2024-01-03 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20231219_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedanswer',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectedanswer_set', to='exam.Result'),
        ),
    ]
